controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
search_products:
    path: /search
    controller: App\Controller\ProduitsController::search
